-- Run this in Supabase SQL Editor

-- 1. Interactions Table (Consolidated for Analytics)
create table public.interactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id text,
  question text,
  answer text,
  language text,
  metadata jsonb
);

-- 2. Crops Table (For price data)
create table public.crops (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  marathi_name text,
  market_price numeric,
  price_trend text, -- 'up' or 'down'
  image_url text
);

-- 3. Security Policies (RLS)
alter table public.interactions enable row level security;
alter table public.crops enable row level security;

-- Allow public insert to interactions (for demo purposes, usually specific to auth user)
create policy "Allow generic insert"
on public.interactions for insert
with check (true);

-- Allow public read for crops
create policy "Allow public read crops"
on public.crops for select
using (true);
