-- SMART FARM PRODUCTION SCHEMA (Supabase/PostgreSQL)
-- Defines the complete ecosystem: Users, Shops, Marketplace, Jobs, and AI Logs.

-- 1. USERS & PROFILES (Extends Supabase Auth)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  role text check (role in ('farmer', 'shop_owner', 'worker', 'admin')) not null,
  full_name text,
  phone text unique,
  village text,
  district text,
  language text default 'en',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Flexible JSON for role-specific data
  -- Farmers: { land_size, crop_type, irrigation_source }
  -- Workers: { skills: ['harvesting', 'tilling'], availability: true }
  additional_data jsonb default '{}'::jsonb
);

-- 2. SHOPS (For Shop Owners)
create table public.shops (
  id bigint generated by default as identity primary key,
  owner_id uuid references public.profiles(id) not null,
  name text not null,
  category text, -- 'Fertilizer', 'Seeds', 'Machinery'
  location text,
  contact_number text,
  is_verified boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. PRODUCTS (Marketplace Inventory)
create table public.products (
  id bigint generated by default as identity primary key,
  shop_id bigint references public.shops(id) on delete cascade not null,
  name text not null,
  description text,
  price numeric not null,
  stock_status text check (stock_status in ('in_stock', 'out_of_stock')) default 'in_stock',
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. JOBS (Labour Hiring System)
create table public.jobs (
  id bigint generated by default as identity primary key,
  employer_id uuid references public.profiles(id) not null, -- Farmer interacting
  title text not null, -- e.g., "Need 5 people for Cotton Picking"
  description text,
  wage_per_day numeric,
  location text,
  status text check (status in ('open', 'closed')) default 'open',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. AI INTERACTIONS (Intelligence Layer Log)
create table public.ai_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  query_text text,
  response_text text,
  audio_url text,
  sentiment text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ROW LEVEL SECURITY (RLS) - "Security Expert" Configuration

-- Enable RLS on all tables
alter table public.profiles enable row level security;
alter table public.shops enable row level security;
alter table public.products enable row level security;
alter table public.jobs enable row level security;
alter table public.ai_logs enable row level security;

-- PROFILES:
-- Public can read basic profile info (needed for job listings/shop owners), User can edit own.
create policy "Public profiles are viewable by everyone" on public.profiles for select using (true);
create policy "Users can insert their own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

-- SHOPS:
-- Everyone can view shops. Only owners can edit.
create policy "Shops are viewable by everyone" on public.shops for select using (true);
create policy "Shop owners can insert shops" on public.shops for insert with check (auth.uid() = owner_id);
create policy "Shop owners can update own shops" on public.shops for update using (auth.uid() = owner_id);

-- PRODUCTS:
-- Everyone can view products. Shop owners manage their own.
create policy "Products viewable by everyone" on public.products for select using (true);
create policy "Shop owners manage products" on public.products for all using (
  exists (select 1 from public.shops where id = products.shop_id and owner_id = auth.uid())
);

-- JOBS:
-- Everyone can view jobs. Farmers manage their own.
create policy "Jobs viewable by everyone" on public.jobs for select using (true);
create policy "Farmers manage jobs" on public.jobs for all using (auth.uid() = employer_id);

-- AI LOGS:
-- Users see their own history only.
create policy "Users see own logs" on public.ai_logs for select using (auth.uid() = user_id);
create policy "Users insert own logs" on public.ai_logs for insert with check (auth.uid() = user_id);

