-- Run this in your Supabase SQL Editor

-- 1. Create Crops Table
create table public.crops (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  marathi_name text,
  market_price numeric,
  price_trend text, -- 'up' or 'down'
  image_url text
);

-- 2. Insert Mock Data (So it's not empty)
insert into public.crops (name, marathi_name, market_price, price_trend)
values
  ('Soybean', 'सोयाबीन', 4800, 'up'),
  ('Cotton', 'कापूस', 6950, 'down'),
  ('Onion', 'कांदा', 2200, 'up'),
  ('Turmeric', 'हळद', 7500, 'stable');

-- 3. Enable Public Read Access (For now)
alter table public.crops enable row level security;

create policy "Enable read access for all users"
on public.crops for select
using (true);
